apiVersion: v1
items:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: s2i-builderimage-sample
    lables:
      app: s2i-builderimage-sample
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: s2i-builderimage-sample
    lables:
      app: s2i-builderimage-sample
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: s2i-builderimage-sample:latest
    source:
      type: Git 
      git:
        uri: "https://github.com/hasegawa-yusuke/sandbox.git"
      contextDir: customBuilderImageSample
    strategy:
      dockerStrategy:
      type: Docker
kind: List
metadata: {}
